# Nodejs stable image is used
FROM node:14

# Set the working directory in the container
WORKDIR /app



# Copy the build artifacts from the Jenkins workspace to the container
COPY ./dist /app
# copy all the files from repository to container
COPY . .


# Expose the port on which the application will be served
EXPOSE 5000

#This Command to serve the build artifacts
CMD ["npm", "start", "dist", "-l", "5000"]
